apiVersion: v1
kind: Secret
metadata:
  name: docker-push
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/ # change this value if using a different Docker registry (exclude namespace)
type: kubernetes.io/basic-auth
stringData:
  username: <username>/<token>
  password: <password>/<token value>